default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: navishai_lab_development

test:
  <<: *default
  database: navishai_lab_test

production:
  primary: &primary_production
    <<: *default
    database: navishai_lab_production
    username: <%= ENV.fetch("NAVISHAI_DATABASE_USERNAME", "navishai") %>
    password: <%= ENV["NAVISHAI_DATABASE_PASSWORD"] %>
    host: <%= ENV["NAVISHAI_DATABASE_HOST"] %>
    port: <%= ENV["NAVISHAI_DATABASE_PORT"] %>
  cache:
    <<: *primary_production
    database: navishai_lab_production_cache
    migrations_paths: db/cache_migrate
    schema_format: ruby
  queue:
    <<: *primary_production
    database: navishai_lab_production_queue
    migrations_paths: db/queue_migrate
    schema_format: ruby
  cable:
    <<: *primary_production
    database: navishai_lab_production_cable
    migrations_paths: db/cable_migrate
    schema_format: ruby
